# Can set active profile using ... application.yaml
#spring.profiles.active=prodProfile2,myCustomProfile

---
spring:
  config:
    activate:
      on-profile: default
  mvc:
    hiddenmethod:
      filter:
        enabled: true

  # kelias į DB (in memory, ram'uose).
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    # default user
    username: admin
    # default password
    password: password


  # jeigu kas nors netinka duombazeje - tegu Hibernate pataiso automatiskai. Jei viskas OK - tegu neliecia
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  mail:
    host: mail.inbox.lt
    port: 587
    username: mantas.sasnauskas@inbox.lt
    password: 6KPdWDw7r4
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

# Disable whitelabel error pages
server:
  error:
    whitelabel:
      enabled: false

---
spring:
  config:
    activate:
      on-profile: testProfile
  mvc:
    hiddenmethod:
      filter:
        enabled: true

  # kelias į DB (in memory, ram'uose).
  datasource:
    url: "jdbc:h2:mem:h2_db"
    # default user
    username: admin
    # default password
    password:


  # jeigu kas nors netinka duombazeje - tegu Hibernate pataiso automatiskai. Jei viskas OK - tegu neliecia
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    show-sql: true


  # įjungti H2 WEB konsolę
  h2:
    console:
      enabled: true
      # H2 web konsolės adresas (URL)
      path: /h2


  mail:
    host: mail.inbox.lt
    port: 587
    username: mantas.sasnauskas@inbox.lt
    password: 6KPdWDw7r4
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

  messages:
    basename: messages

# Disable whitelabel error pages
server:
  error:
    whitelabel:
      enabled: false

---
spring:
  config:
    activate:
      on-profile: in_docker

  # kelias į DB (in memory, ram'uose).
  datasource:
    url: "${DATABASE_URL}"
    # default user
    username: "${DATABASE_USERNAME}"
    # default password
    password: "${DATABASE_PASSWORD}"

  # nurodom kita DB dialekta
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
