create table devices
(
    id           bigint generated by default as identity,
    comment      varchar(255),
    create_date  date,
    device_id    bigint,
    transport_nr varchar(255),
    user_id      integer,
    primary key (id)
);


create table positions
(
    id        bigint generated by default as identity,
    date      timestamp(6),
    latitude  float(53),
    longitude float(53),
    speed     integer,
    device_id bigint,
    primary key (id)
);

create table users
(
    id       bigint generated by default as identity,
    email    varchar(255),
    login    varchar(255),
    password varchar(255),
    role     varchar(255),
    primary key (id)
);